### PR TITLE
Fix QoS on Humble

### PR DESCRIPTION
**Pull request by danthony06**
@tonynajjar I had problems building your solution with Foxy because that struct isn't defined until Humble. Does this conditionally compiled solution look good to you?

### CODE REVIEW

**Comment by tonynajjar** [comment]
Looks good! One minor detail though I would have loved to be the fix contributor. I'm trying to up my open source game 😁

**Comment by danthony06** [comment]
I'm perfectly happy to give you credit if you want want to submit a fix that does something similar. As long as it's working for Foxy and Humble, I'm okay with it.

**Comment by tonynajjar** [comment]
I was just testing it. While it does work, I'm confused why the durability is Volatile and not Transient_local; this should not be a problem though

```
Subscription count: 1

Node name: swri_console_1677166596024417509
Node namespace: /
Topic type: rcl_interfaces/msg/Log
Endpoint type: SUBSCRIPTION
GID: 01.10.1c.eb.73.3b.74.ea.a2.96.b2.0c.00.00.15.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (1000)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite
```

**Comment by tonynajjar** [comment]
Also, It would be nice to release this for the next ROS sync as it's a pretty important bug

**Comment by tonynajjar** [comment]
Yep, exactly my thought, however according to the [QoS compatibility table](https://docs.ros.org/en/rolling/Concepts/About-Quality-of-Service-Settings.html#:~:text=No-,Transient%20local,Volatile,-Yes), it should not cause any issues

**Comment by danthony06** [comment]
Okay, I've bloomed this for Foxy, Humble, and Rolling

https://github.com/ros/rosdistro/pull/36278
https://github.com/ros/rosdistro/pull/36279
https://github.com/ros/rosdistro/pull/36280

**Pull request merged**
