### PR TITLE
Replace deprecated is_initialized() with ok()

### PR DESCRIPTION
**Pull request by Timple**
Perhaps `dashing-devel` isn't the best branch for this? But it's the only ROS2 branch present it seems.
This should fix [galactic](https://github.com/ros2/rclcpp/pull/1622/files#diff-40a81900d813b0824db3259f66b5667ca6684ba6c8d24d6a85b9f8904ef4e1a0L159).

### CODE REVIEW

**Comment by danthony06** [comment]
Currently we're using branch names to indicate the minimum required version of ROS1/2 to support. Since this is a Galactic specific feature, it looks like we'll need to fork a ```galactic``` branch off of the ```dashing-devel``` and merge it into that branch. Before we do that, let me look at some of the other PRs and issues that have accumulated that might apply to multiple ROS2 versions, so that we avoid having to re-do changes in multiple branches.

**Comment by Timple** [comment]
This change also works for `foxy`. As `is_initialized()` was already deprecated there. And of course `rolling` since that one is ahead.

So basically it works for all active ROS2 distributions. Maybe go for a default ros2 branch (`ros2` / `main` / `rolling`?). And only split off if breaking changes are introduced.

**Comment by pjreed** [comment]
Yeah, since Foxy is the oldest supported distro, I think at this point it'd make the most sense to have a `ros2-devel` branch that is used for active development and only create distro-specific branches when necessary.

**Comment by Timple** [comment]
Done

**Pull request merged**
